config/routes.rb
Rails31PreparedStatements::Application.routes.draw do
  resources :people do
    collection do
      get "filter_form"
      get "filter"
    end
  end

  get "sql_area/cached_person_queries"

  post "sql_area/flush_query_cache"
  post "sql_area/set_cursor_sharing_to_exact"
  post "sql_area/set_cursor_sharing_to_force"
end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/models/sql_area.rb
class SqlArea < ActiveRecord::Base
  def self.cached_person_queries
    SqlArea.connection.select_all(
      "select  sql_text
       from    sys.v_$sqlarea
       where   sql_text like '%PEOPLE%'
       and     sql_text not like '%sqlarea'
       and     sql_text not like '%sqlarea%'
       and     sql_text not like '%all_constraints%'
       and     sql_text not like '%all_tab_cols%'
       and     sql_text not like '%all_triggers%'
       order by last_load_time"
       )
  end

  def self.set_cursor_sharing_to_exact
    SqlArea.connection.execute "alter session set cursor_sharing = 'EXACT'"
  end

  def self.set_cursor_sharing_to_force
    SqlArea.connection.execute "alter session set cursor_sharing = 'FORCE'"
  end

  def self.flush_query_cache
    SqlArea.connection.execute "alter system flush shared_pool"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
    render :partial => 'person', :locals => { :person => @person }
  end

  def new
    @person = Person.new
  end

  def edit
    @person = Person.find(params[:id])
    render :partial => 'form', :locals => { :person => @person }
  end

  def create
    @person = Person.new(params[:person])
    @person.save
  end

  def update
    @person = Person.find(params[:id])
    @person.update_attributes(params[:person])
    render :nothing => true
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy
    render :nothing => true
  end

  def filter_form
  end

  def filter
    filter_params = params.select {|k,v| k =~ /filter/ && v != ""}
    if filter_params.size > 0
      filter_names = filter_params.keys.map {|k| k.slice(7..-1)}
      filter_values = filter_params.values
      filter_method = "find_all_by_" + filter_names.join("_and_")
      @people = Person.send filter_method, *filter_values
    else
      @people = Person.all
    end
  end
end

app/controllers/sql_area_controller.rb
class SqlAreaController < ActionController::Base
  protect_from_forgery

  def cached_person_queries
    @cached_person_queries = SqlArea.cached_person_queries
    puts @cached_person_queries.length

    respond_to do |format|
      format.js
    end
  end

  def flush_query_cache
    SqlArea.flush_query_cache
    redirect_to :action => :cached_person_queries
  end

  def set_cursor_sharing_to_exact
    SqlArea.set_cursor_sharing_to_exact
    render :nothing => true
  end

  def set_cursor_sharing_to_force
    SqlArea.set_cursor_sharing_to_force
    render :nothing => true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Demonstration of Rails 3.1/ActiveRecord and Oracle</title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_filter_form.html.erb
<%= form_tag '/people/filter', :method => :get, :remote => true, :id => "people-filter-form" do %>
    <table>
        <tr>
            <td class="person-name">
                <%= text_field_tag 'filter_last_name', nil, :size => 22 %>
            </td>
            <td class="person-name">
                <%= text_field_tag 'filter_first_name', nil, :size => 22 %>
            </td>
            <td class="person-ssn">
                <%= text_field_tag 'filter_ssn', nil, :size => 11 %>
            </td>
            <td class="person-age">
                <%= text_field_tag 'filter_age', nil, :size => 2 %>
            </td>
            <td class="button-column">
                <%= submit_tag 'Apply', :id => 'filter-apply-button' %>
            </td>
            <td class="button-column">
                <%= button_tag 'Cancel', :id => 'filter-cancel-button', :type => 'button' %>
            </td>
        </tr>
    </table>
<% end %>

app/views/people/_form.html.erb
<td colspan="5">
    <%= form_for person, :remote => true do |f| %>
        <table>
            <tr>
                <td class="person-name">
                    <%= f.text_field :last_name, :size => 22 %>
                </td>
                <td class="person-name">
                    <%= f.text_field :first_name, :size => 22 %>
                </td>
                <td class="person-ssn">
                    <%= f.text_field :ssn, :size => 11 %>
                </td>
                <td class="person-age">
                    <%= f.text_field :age, :size => 2 %>
                </td>
                <td class="button-column">
                    <%= f.submit 'Save'  %>
                </td>
            </tr>
        </table>
    <% end %>
</td>
<td class="button-column">
    <% if person.persisted? %>
       <%= button_tag 'Done', :class => 'update-cancel-button', :url => person_path(person) %>
    <% else %>
       <%= button_tag 'Cancel', :id => 'cancel-button' %>
    <% end %>
</td>

app/views/people/_people.html.erb
<table id="people">
    <tr>
        <th>Last name</th>
        <th>First name</th>
        <th>Ssn</th>
        <th>Age</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
    </tr>

    <% @people.each do |person| %>
        <%= render :partial => 'person', :locals => {:person => person} %>
    <% end %>
</table>

app/views/people/_person.html.erb
<tr id="person-row">
    <td class="person-name"><%= person.last_name %></td>
    <td class="person-name"><%= person.first_name %></td>
    <td class="person-ssn"><%= person.ssn %></td>
    <td class="person-age"><%= person.age %></td>
    <td class="button-column"><%= button_to 'Edit', edit_person_path(person), {:method => :get, :class => 'edit-person-button', :url => edit_person_path(person)} %></td>
    <td class="button-column"><%= button_to "Delete", person_path(person), {:confirm => 'Are you sure?', :remote => true, :method => :delete, :form_class => 'delete-person-form'} %>
</tr>

app/views/people/create.js.erb
<%- if @person.valid? %>
  $("#people").find('tbody').append("<%= escape_javascript(render(:partial => 'person', :locals => { :person => @person })) %>") ;
  $("#person-form-area").html("") ;
  $('#cached-queries-button').trigger('click') ;
<%- else %>
  $("#person-form-area").html("<%= escape_javascript(render(:partial => 'form', :locals => { :person => @person })) %>")
<%- end %>

app/views/people/edit.html.erb
<%= render(:partial => "form", :locals => { :person => @person }) %>

app/views/people/filter.js.erb
$("#people-rows").html("<%= escape_javascript(render(:partial => "people")) %>")

app/views/people/filter_form.js.erb
$("#person-form-area").html("<%= escape_javascript(render(:partial => "filter_form")) %>")

app/views/people/index.html.erb
<div id="content">
    <div id="header">
        <h1>Demonstration of Rails 3.1/ActiveRecord and Oracle</h1>
    </div>

<fieldset id='people-fields'>
    <legend>People</legend>
    <div id="people-actions">
        <%= button_to "Create new people", {:controller => :people, :action => :new}, {:remote => true, :method => :get, :id => 'new-person-button'} %>
        <%= button_to "Filter people", {:controller => :people, :action => :filter_form}, {:remote => true, :method => :get, :id => 'people-filter-button'} %>
    </div>

    <div id="people-rows">
        <%= render :partial => 'people' %>
    </div>

    <div id="person-form-area"></div>
</fieldset>

<fieldset id="cached-queries">
    <legend>Oracle SQL query cache</legend>
    <div id="sql-area-actions">
        <%= button_to "Show cached queries", {:controller => :sql_area, :action => :cached_person_queries}, {:remote => true, :method => :get, :id => 'cached-queries-button'} %>
        <%= button_to "Flush query cache", {:controller => :sql_area, :action => :flush_query_cache}, {:remote => true, :method => :post} %>
        <%= button_to "Set cursor sharing to EXACT", {:controller => :sql_area, :action => :set_cursor_sharing_to_exact}, {:remote => true, :method => :post} %>
        <%= button_to "Set cursor sharing to FORCE", {:controller => :sql_area, :action => :set_cursor_sharing_to_force}, {:remote => true, :method => :post} %>
    </div>

    <div id="cached_person_queries"></div>
</fieldset>
</div>

app/views/people/new.js.erb
$("#new-people-button").hide()
$("#person-form-area").html("<%= escape_javascript(render(:partial => "form", :locals => { :person => @person })) %>")

app/views/sql_area/_cached_person_queries.html.erb
<table>
<% @cached_person_queries.each do |q| %>
    <tr>
        <% if q["sql_text"] =~ /SELECT/ %>
            <td class="selectSQL">
        <% elsif q["sql_text"] =~ /INSERT/ %>
            <td class="insertSQL">
        <% elsif q["sql_text"] =~ /UPDATE/ %>
            <td class="updateSQL">
        <% elsif q["sql_text"] =~ /DELETE/ %>
            <td class="deleteSQL">
        <% end %>
            <%= q["sql_text"] %>
        </td>
    </tr>
<% end %>
</table>

app/views/sql_area/cached_person_queries.js.erb
 $("#cached_person_queries").html("<%= escape_javascript(render(:partial => 'cached_person_queries', :locals => { :cached_person_queries => @cached_person_queries })) %>")